<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.dX8oWEV' shared service.

return $this->privates['.service_locator.dX8oWEV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'episode' => ['privates', '.errored..service_locator.dX8oWEV.App\\Entity\\Episodes', NULL, 'Cannot autowire service ".service_locator.dX8oWEV": it references class "App\\Entity\\Episodes" but no such service exists.'],
], [
    'episode' => 'App\\Entity\\Episodes',
]);
