<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.qNhmoAu' shared service.

return $this->privates['.service_locator.qNhmoAu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'episodes' => ['privates', '.errored..service_locator.qNhmoAu.App\\Entity\\Episodes', NULL, 'Cannot autowire service ".service_locator.qNhmoAu": it references class "App\\Entity\\Episodes" but no such service exists.'],
], [
    'episodes' => 'App\\Entity\\Episodes',
]);
