<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.yrDeEqb' shared service.

return $this->privates['.service_locator.yrDeEqb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'programRepository' => ['privates', 'App\\Repository\\ProgramRepository', 'getProgramRepositoryService.php', true],
    'seasonRepository' => ['privates', 'App\\Repository\\SeasonRepository', 'getSeasonRepositoryService.php', true],
], [
    'programRepository' => 'App\\Repository\\ProgramRepository',
    'seasonRepository' => 'App\\Repository\\SeasonRepository',
]);
