<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMxun8ui\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMxun8ui/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMxun8ui.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMxun8ui\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMxun8ui\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Mxun8ui',
    'container.build_id' => '9223b07a',
    'container.build_time' => 1578392637,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMxun8ui');
