<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE8Ycxea\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE8Ycxea/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE8Ycxea.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE8Ycxea\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerE8Ycxea\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'E8Ycxea',
    'container.build_id' => '78f65860',
    'container.build_time' => 1576165379,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE8Ycxea');
